### PR TITLE
Enable realtime collaboration

### PR DESCRIPTION
**Pull request by yuvipanda**
- Adds https://pypi.org/project/jupyterlab-link-share/ so users can
  provide *authenticated* links to other users that lets them
  collaborate in real time
- Turn on the real time collaboration flag in JupyterLab

This will allow realtime collaboration in both JupyterLab and
RetroLab

### CODE REVIEW

**Comment by yuvipanda** [comment]
What advantage does the automatic tag update give? It means I can't push any changes without pulling again...

**Comment by chicocvenancio** [comment]
>What advantage does the automatic tag update give? 
we can pull the PR and helm apply directly.

>It means I can't push any changes without pulling again...
yeah, not great. Not sure how to balance the concerns here.

**Comment by yuvipanda** [comment]
This adds a menu item:

image

when selected, it gives you a link:

image

You share that link with someone else, and they can collaborate with you real time! They can also execute code tho, so be careful who you give the link to.

**Comment by chicocvenancio** [comment]
Works well locally.

I'd appreciate a bit more discussion on the security aspects though. The biggest one I can think of is that this will allow anyone with the link to make edits to wikimedia projects on behalf of the user who started the server. Not sure that will be clear to users.

**Comment by yuvipanda** [comment]
@chicocvenancio i agree! I added the text to the dialog box to warn users of this. What more do you think can be added?

**Comment by yuvipanda** [comment]
Or in more specific terms @chicocvenancio, what would be next steps in getting this merged?

**Comment by chicocvenancio** [comment]
>Or in more specific terms @chicocvenancio, what would be next steps in getting this merged?

I would just like some sanity check from @bd808, @dipietrom or @david-caro.

**Comment by dipietrom** [comment]
I'm not sure what more can be done to increase security beyond the dialog box. We're in a fairly low stakes situation as anyone could create their own user if they wanted to do anything, as such I wouldn't expect much abuse to come from trying to get access to other people's servers.

**Review by dipietrom — APPROVED** [review]

**Comment by yuvipanda** [comment]
@dipietrom the issue is that users get access to their SUL account credentials, so if you were to trick someone into sharing their URL with you, you can make edits as them.

**Comment by dipietrom** [comment]
Oh, I did not understand that from the message that the share link provides. Can we make an edit on the PAWS level that makes it clear that sharing the link allows whoever has it to make edits as the original user? Such an edit I would imagine would be inappropriate on the jupyterlab-link-share level, as I wouldn't expect it to apply the same way to most deployments.

**Comment by vivian-rook** [comment]
image
I'm not seeing the Share link as above when I run in minikube. 

I believe I have the right container:
```
$ kubectl get -o yaml pod/jupyter--56-52ook-5f-28-57-4d-46-29 | grep image
    image: quay.io/wikimedia-paws-prod/singleuser:pr-119
    imagePullPolicy: Always
    image: quay.io/wikimedia-paws-prod/singleuser:pr-119
```

**Comment by chicocvenancio** [comment]
Only available for jupyterlab, the url `s/tree/lab/` trick will do it.

**Comment by vivian-rook** [comment]
There it is! Just voted up moving to lab in https://phabricator.wikimedia.org/T295043

**Comment by aborrero** [comment]
> I'd appreciate a bit more discussion on the security aspects though. The biggest one I can think of is that this will allow anyone with the link to make edits to wikimedia projects on behalf of the user who started the server. Not sure that will be clear to users.

I understand the dilemma. But worst case the wikis can revert the rogue edits. The PAWS user can also easily stop the live-sharing feature.

Personally, the collaborative potential of this tools may outweighs the risk of someone not using the tool properly (or being tricked into to don't using it properly). Also we can easily rollback the feature if we see some full scale abuse.

Summary: +1

**Comment by david-caro** [comment]
LGTM, +1

I would add a note somewhere in wikitech specifying the steps (or step xd) to revoke the sharing link, just in case as the showing of the dialogue might happen way before the abuse is noticed and the user might forget.

**Review by david-caro — APPROVED** [review]

**Pull request merged**
