### PR TITLE
Prepare for multi-instance wiki replicas

### PR DESCRIPTION
**Pull request by crookedstorm**
The ability to query the wikireplicas is very important to PAWS. In order to continue using them after they are refactored, PAWS needs to be able to proxy requests to the correct backend on connect. The handy thing is that this will work just fine now since all requests go to the same cluster of instances right now--besides a possible performance hit on connect, this should just work with the existing setup.

Besides setting up the new mysql-proxy lua, this also sets up a minikube development environment with a self-contained OAUTH workflow (using the Bitnami Mediawiki and Mariadb charts) to make hacking on PAWS pretty safe. I used this development environment to confirm this works.

Another big change is that I have moved a number of values out of values.yaml and into secrets.yaml. The reason is that a production deployment will override anything in values.yaml with what is in secrets.yaml, so what is in values.yaml should be whatever is most convenient for development rather than what is needed in production.

Please review away!

### CODE REVIEW

**Comment by crookedstorm** [comment]
Looks like I have some CI-motivated changes to make. I wonder if there's anything I forgot to commit. Either way, I'll fix that before review is necessary.

**Comment by crookedstorm** [comment]
Python lint cleared up, but it appears that what I did in my helm template is only valid for helm > 3.3.0. I will look into providing a sane default tomorrow since it doesn't work using the version of helm that is installed on the cluster right now. The version we will be installing after the next k8s upgrade is the same version I targeted this at, but I think it is possible to prevent this bug from affecting the earlier version.

**Comment by crookedstorm** [comment]
I believe the failure is actually a bug in helm. That may hold back this PR until after we upgrade Kubernetes and Helm on PAWS.

**Comment by chicocvenancio** [comment]
I love this PR, especially the added ability to do local testing with the local MediaWiki instance and oAuth setup.

One thing I think we should think through a bit more is the use of `secrets.yaml` to override `values.yaml`. 
I appreciate the idea of leaving defaults for the dev environment that are overridden in production, but I am a little concerned about using `secrets.yaml` to do this. 

My concern is about visibility, both in terms of having our source code open and in terms of having adequate review of configuration changes. 
Being encrypted, for security reasons, `secrets.yaml` will not be visible for most contributors and I feel this means we should limit its content to security-sensitive tokens.

Perhaps we could add a third `production.yaml` or `WMCS.yaml` with values that are not security-sensitive?

**Comment by crookedstorm** [comment]
> 
> Perhaps we could add a third `production.yaml` or `WMCS.yaml` with values that are not security-sensitive?

I think that's a good idea. We are allowed to use multiple values file args in helm. We'll just have to be careful not to duplicate any in secrets.yaml.  I'll add that to this.

**Comment by crookedstorm** [comment]
I have separated out the "prod overrides" into paws/production.yaml and now this PR has no secrets.yaml changes to it. We should be able to deploy using `helm -n prod upgrade paws -f secrets.yaml -f production.yaml` with this method (and when repairing the deployhook, it'll need to do that too). So now, I'm still blocked on the version of helm.
```yaml
persistentVolumeClaim:
            claimName: {{ if .Values.mediawiki.persistence.existingClaim }}{{ .Values.mediawiki.persistence.existingClaim }}{{- else }}{{ template "mediawiki.fullname" . }}-mediawiki-mediawiki{{- end }}
```
This still triggers a bug in helm for 3.2.0. The latest helm works as does the staged upgrade in our apt component repo. However, to upgrade to it, we'd also need to switch repos for Kubernetes (which is planned). We could, perhaps also backport it into our 1.16 repo.  Hmm. I might be able to un-nest the values with a `with` statement. I'll try that. That should work in all versions.

**Comment by crookedstorm** [comment]
Yay! The check works. However, this failed the docker build phase because Github ratelimited the travis job because I have that "before_install" bit running before _every_ job of the CI build. I'll put up one more patch to fix that.

**Comment by crookedstorm** [comment]
There! This finally passes the tests and things and has evidence that it will work.  Please provide any reviews!

**Review by chicocvenancio — APPROVED** [review]
LGTM.

**Pull request merged**
