### PR TITLE
move to jupyterlab

### PR DESCRIPTION
**Pull request by vivian-rook**
Not sure if we would want to announce this some before sending it out. The interface would be, suddenly, different.
https://phabricator.wikimedia.org/T295043

### CODE REVIEW

**Comment by yuvipanda** [comment]
here's my suggested method for doing this:

1. Set `singleuser.defaultUrl` in https://github.com/toolforge/paws/blob/246e2afa97060dbd010b5a36ac88589f972d741f/paws/values.yaml#L277 to be `/lab` so the *default* UI is JupyterLab
2. Install [retrolab](https://github.com/jupyterlab/retrolab) as well, primarily because it provides an [interface switcher](https://github.com/jupyterlab/retrolab/pull/158) that lets you switch between classic notebook, retrolab and jupyterlab.
3. Make an announcement that the *default* is what is being switched, and this won't affect what is available.
4.

**Comment by yuvipanda** [comment]
There is still a lot of extensions and what not that work in classic notebook but don't have equivalents in jupyterlab, so keeping the classic around is helpful

**Comment by vivian-rook** [comment]
Seems reasonable. Not sure if we will need the redirect as it would appear the default default is /lab.

**Comment by chicocvenancio** [comment]
Yeah, I think jupyterhub 2 changed the default, so by upgrading we're changing it.

Maybe we should write a small announcement and link to it from the [banner](https://github.com/toolforge/paws/blob/6d0dba0456b52353d631b87ce266dd81b8ae6e31/paws/values.yaml#L248-L252)?

**Comment by vivian-rook** [comment]
We could update the banner, though I would expect anyone already logged in would not see it, as, I believe, the banner page would be skipped at that point. Perhaps a message out to cloud-announce?

**Comment by chicocvenancio** [comment]
The banner is visible on the server lauch page, so everyone should see it eventually. Not sure if currently running servers are restated?

But yeah, we should announce in cloud-announce and probably the tech newsletter as well.

**Comment by vivian-rook** [comment]
https://github.com/toolforge/paws/pull/135 for a potential banner update. Added a line to the newsletter about updating the interface (https://www.mediawiki.org/wiki/Technical_Community_Newsletter/2022/April) how long do we want to wait after sending to cloud-announce before merging this? Two weeks?

**Comment by vivian-rook** [comment]
Unless there are any objections, my plan is to merge https://github.com/toolforge/paws/pull/135
Send a note to cloud-announce linking to https://phabricator.wikimedia.org/T295043 and announcing that the update will go out on the 21st. And sending the same to tech news, such that the news should come out on the 14th giving a week for anyone to notice.

If this all sounds alright, if I could get an approval on this and https://github.com/toolforge/paws/pull/135 I'll get things in motion.

**Review by chicocvenancio — APPROVED** [review]

**Pull request merged**
