### PR TITLE
hub database: move from ToolsDB to Trove

### PR DESCRIPTION
**Pull request by crookedstorm**
Trove has been deployed for a bit. Since we don't have replication or
backups for it in WMCS yet, I've set up an instance that backs up
mysql dumps to NFS. Honestly, the data is likely far safer there than
in ToolsDB in my opinion.

Please note, this is already deployed to settle a security issue.

Bug: T289180

### CODE REVIEW

**Comment by crookedstorm** [comment]
At this point deploying to ToolsDB will not work because I changed the password anyway. I'm leaving this up for review for a bit just for awareness.

**Comment by supertassu** [comment]
I can't really do any meaningful reviews here without the ability to see the contents of that encrypted file, but I don't see issues with you just merging this if it just contains already-live changes to the database credentials and hostname.

**Review by chicocvenancio — APPROVED** [review]
LGTM

**Comment by chicocvenancio** [comment]
@supertassu yeah, just changes the db url, with password and host changes. You might already have access to the key to decrypt this, btw. We could create a task to figure it out.

@crookedstorm could I be added to T289180?

**Comment by supertassu** [comment]
> yeah, just changes the db url, with password and host changes. You might already have access to the key to decrypt this, btw. We could create a task to figure it out.

I guess there's some key on the Cloud VPS VMs that I could use too, but my [personal key](https://taavi.wtf/pgp.txt) doesn't have access afaik.

> could I be added to T289180?

(same for me, thanks)

**Comment by chicocvenancio** [comment]
> I guess there's some key on the Cloud VPS VMs that I could use too

I think its the only key setup to be used here.

**Comment by crookedstorm** [comment]
@supertassu Yeah, right now, we've been using a shared key setup from https://github.com/AGWA/git-crypt. We haven't changed to doing individual keys on it yet, though it would be a good thing to do eventually.

**Pull request merged**
