### PR TITLE
Adding Library support in PAWS

### PR DESCRIPTION
**Pull request by Enabuufu**
Adding Library support in PAWS

### CODE REVIEW

**Comment by aborrero** [comment]
This PR apparently includes a number of Merge commits that I would love not to include in our resulting git history tree.

Moreover, this seems to include a binary .ODT file and other random file "Adding library support in paws". Please cleanup this pull request. Ideally this will contain exactly 1 commit, with the updates to the README.md file.

**Comment by Enabuufu** [comment]
alright thanks for the comment
, let me remove the unnecessary files, so does it mean i open another PR to reflect the changes?

**Comment by aborrero** [comment]
> alright thanks for the comment
> , let me remove the unnecessary files, so does it mean i open another PR to reflect the changes?

Yes, another PR is fine. You can close the PRs that are no longer valid or relevant.

**Comment by Enabuufu** [comment]
Alright I have submitted a new pull request, named update readme.md, please
review it

And I will close the irrelevant ones soon

**Pull request closed without merging**
