### PR TITLE
Add visualization + app building packages

### PR DESCRIPTION
**Pull request by yuvipanda**
- holoviews (panel), dash (plotly) and streamlit are similar to
  voila, in helping build 'dashboard' style interfaces that can
  be used without needing to write code.
- flask & fastapi can be used to develop and build servers that
  provide a similar experience as a dashboard, but with more work

### CODE REVIEW

**Comment by yuvipanda** [comment]
Based on conversations with @chicocvenancio, @fuzheado and Tina in the Jupyter / GLAM reconciliation group

**Review by chicocvenancio — APPROVED** [review]
LGTM

**Comment by yuvipanda** [comment]
@chicocvenancio does merging automatically build and push this? Or is that manual still?

**Comment by chicocvenancio** [comment]
> @chicocvenancio does merging automatically build and push this? Or is that manual still?

Builds and pushes, but with the git commit tag only. To deploy we need to tag with latest (quay.io allows us to do this from the web ui).

**Pull request merged**
