### PR TITLE
Move from travis CI to GitHub actions

### PR DESCRIPTION
**Pull request by yuvipanda**
- Travis CI is slowly dying
- GitHub actions has better abstractions in terms of re-usable actions

### CODE REVIEW

**Comment by crookedstorm** [comment]
I did set the cluster to always pull (even with latest tag it didn't do that by default)...I'm waffling a little because of the possibility of surprise issues with unclear rollback when everyone is looking at something else. This might be a good idea. I think I like it better if it tags with the commit hash (or similar nonsense) AND tags the same image with latest. I wasn't doing that yet, but that way we can change the latest tag by hand if needed really badly, change back, etc. without an actual build.

**Comment by crookedstorm** [comment]
Looking back, I see commit-based tags already. I think we might already be pushing the non-latest tag, which would mean what I said is potentially the real nonsense! :) Tagging the image with latest and pushing it would be all that is needed if so.

**Comment by crookedstorm** [comment]
Yes the current travis build does that. https://github.com/toolforge/paws/blob/master/travis-script.bash When branch is master that runs. It just doesn't tag with latest.

**Comment by crookedstorm** [comment]
I don't like that this will complicate things by running both a travis build AND a github workflow. Would it be possible to put this into the travis ci build instead? That or move the travis builds here to github workflows?

**Review by crookedstorm — CHANGES_REQUESTED** [review]
Sorry, this isn't gerrit, so I'm not used to the comment flow, but to make this an official review:
I really don't like this being a separate toolchain from the rest of the CI. I think this might be better than the Travis script, but I'd rather this either be incorporated into the existing push step in Travis (by adding a tag with latest) or the existing Travis checks also moved into github workflows.

**Comment by crookedstorm** [comment]
Here is what it does, for comparison https://travis-ci.com/github/toolforge/paws/jobs/507175696

**Comment by yuvipanda** [comment]
@crookedstorm ah, totally makes sense. I've moved everything to GitHub actions - I'll fiddle with it to see if I can get it to work.

**Comment by crookedstorm** [comment]
It's passing. Ready for review/merge?

**Comment by yuvipanda** [comment]
@crookedstorm yep!

**Comment by yuvipanda** [comment]
Actually it needs the quay.io credentials put in github secrets before it can be merged, so the 'build and push' action will work

**Comment by chicocvenancio** [comment]
The build.py used by the travis workflow builds more images than this GHA, right?

**Comment by crookedstorm** [comment]
@chicocvenancio The build.py is run by the deployhook, not travis, which is currently disabled. Since travis doesn't trigger deployhook right now, I don't think this needs to. As for what we are building and should we build more, that's another matter.

**Comment by crookedstorm** [comment]
On the topic of what to build, nothing should build the dbproxy image anymore. It's deprecated, but still running for people who don't know and are only using enwiki.

**Comment by crookedstorm** [comment]
I haven't filed the gap left by that in the minikube setup yet. :(

**Comment by crookedstorm** [comment]
Finally reviewed the files. I agree with @chicocvenancio this only seems to be hitting singleuser, and is not building the rest of the images (we probably should ignore new versions of dbproxy and query-killer...and remove query-killer actually). Jobber is only used in minikube, but changes should probably end up live. This isn't as selective as the travis script, is it? Like do we have to define a separate action for each path in case it is in scope?

**Comment by yuvipanda** [comment]
Ah, just realized that build.py was indeed building all the images. I think one action per image is appropriate, since most changes don't touch most images. So I'll build:

1. singleuser
2. hub
3. nbserve
4. renderer
5. jobber

Is that right?

**Comment by crookedstorm** [comment]
I think that's right for now. We can always add deploy-hook later if we fix and re-implement that in a similar way.

**Comment by dipietrom** [comment]
Sorry my github-fu wasn't strong enough to figure out how to continue work on a forked repo. I opened https://github.com/toolforge/paws/pull/98 using this PR as a guide and reauthored lint.yaml back to Yuvi there.

**Comment by dipietrom** [comment]
I believe this was handled in https://github.com/toolforge/paws/pull/98

**Pull request closed without merging**
