### PR TITLE
Remove cull_idle_server from hub image

### PR DESCRIPTION
**Pull request by yuvipanda**
It ships by default with the base hub now.

### CODE REVIEW

**Comment by chicocvenancio** [comment]
>It ships by default with the base hub now.

Is it true in the version we're running?

**Comment by chicocvenancio** [comment]
> Yep! z2jh in some way grew out of paws, and it took this with it :)
Indeed, just the way this script has been provided has moved around a bit. We're not even using this image provided script but the configmap one.

**Comment by crookedstorm** [comment]
I'll merge and deploy this later today.

**Comment by yuvipanda** [comment]
Thanks for the merge and deploy, @crookedstorm!

**Pull request merged**
